

services:
  frontend:
    depends_on:
      - server
    build: ./front-end
    environment:
      VITE_API_URL: http://192.168.18.41:5000
    ports:
      - 5173:5173
    develop:
      watch:
        - path: ./front-end
          target: /app 
          action: sync
        - path: ./front-end/package.json
          action: rebuild
        - path: ./front-end/package-lock.json
          action: rebuild

  server:
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_started
    build: ./Backend
    environment:
      SERVER_PORT: 5000
      CLOUDINARY_CLOUD_NAME: dv9af2izq
      CLOUDINARY_API_KEY: 452547743138638
      CLOUDINARY_API_SECRET: g2r71ozcowsUSmR9d3m26Qpp2_A
      DB_USER: postgres
      DB_HOST: database
      DB_NAME: socialMediaApp
      DB_PASSWORD: abdul12345
      DB_PORT: 5432
      JWT_SECRET: your_jwt_secret_here
      FRONTEND_URL: http://192.168.18.41:5173
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - 5000:5000
    develop:
      watch:
        - path: ./Backend
          target: /app
          action: sync
        - path: ./Backend/package.json
          action: rebuild
        - path: ./Backend/package-lock.json
          action: rebuild

  database:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: abdul12345
      POSTGRES_DB: socialMediaApp
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 10
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  db-data:
  redis-data:
