

services:
  frontend:
    depends_on:
      - server
    build: ./front-end
    environment:
      VITE_API_URL: ${VITE_API_URL}
      VITE_SOCKET_SERVER_URL: ${VITE_SOCKET_SERVER_URL}
    ports:
      - 5174:5173
    develop:
      watch:
        - path: ./front-end
          target: /app 
          action: sync
        - path: ./front-end/package.json
          action: rebuild
        - path: ./front-end/package-lock.json
          action: rebuild

  server:
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_started
      rabbitmq:
        condition: service_started
    build: ./Backend
    environment:
      SERVER_PORT: 5001
      CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}
      DB_USER: ${DB_USER}
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: 5432
      JWT_SECRET: ${JWT_SECRET}
      FRONTEND_URL: ${FRONTEND_URL}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: 6379
      RABBITMQ_URL: amqp://rabbitmq:5672
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - 5001:5000
    develop:
      watch:
        - path: ./Backend
          target: /app
          action: sync
        - path: ./Backend/package.json
          action: rebuild
        - path: ./Backend/package-lock.json
          action: rebuild

  database:
    image: postgres:17
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 10

  socket-server:
    build: ./socketServer
    depends_on:
      server:
        condition: service_started
    environment:
      SERVER_PORT: 4999
      REDIS_URL : ${REDIS_URL}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: 6379
    ports:
      - 4999:4999
    develop:
      watch:
        - path: ./socketServer
          target: /app
          action: sync
        - path: ./socketServer/package.json
          action: rebuild
        - path: ./socketServer/package-lock.json
          action: rebuild

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  rabbitmq:
    image: rabbitmq:3.13-management
    restart: always
    ports:
      # Standard AMQP protocol port
      - "5672:5672"
      # HTTP Management UI port
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      # Ensures your queues and data persist if the container restarts
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
    db-data:
    redis-data:
    rabbitmq_data:
